config {
    schema: "dev",    
    type: "incremental",
    uniqueKey: ["Id"]
}

SELECT
  a.*,
  parse_date('%d/%m/%Y',left(CreatedOn,10)) as CreatedOnDt,
  parse_datetime('%d/%m/%Y %H:%M:%S',CreatedOn) as CreatedOnDtTime
FROM
  `boelpadel.dev.test_bq_schema_from_json5`
CROSS JOIN
  UNNEST(recs) AS a

${when(incremental(),
   `WHERE parse_date('%d/%m/%Y',left(CreatedOn,10)) >= (SELECT cast(DATE_SUB(MAX(CreatedOnDt), INTERVAL 1 MONTH) as DATE) FROM ${self()})`)}

